---
title: "Final Homework"
author: "Juan Mata & Leonardo Masci & Martina Betti & Stefano D'Arrigo"
date: "6/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Just to start...

```{r libraries, echo=FALSE}
library(data.table)
library(factoextra)
```


Import data

```{r import_data}
data <- fread("data/train4final_hw.csv")
```


Dimensions


```{r dimensions}
dim(data)
```


Dimensionality reduction

```{r pca}
res.pca <- prcomp(data)
```


Visualize PCA

```{r pca_viz}
fviz_eig(res.pca)
```



```{r}
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```


```{r}
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```



#TODO: understand plots [http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/118-principal-component-analysis-in-r-prcomp-vs-princomp/]

